-- The Internet Harbor (Supabase / Postgres) schema
-- Idempotent: safe to paste into Supabase SQL Editor multiple times.

-- Extensions (safe if already enabled)
create extension if not exists "pgcrypto";

-- Helper: updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- PROFILES
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  avatar_approved boolean not null default false,
  role text not null default 'user' check (role in ('user', 'admin')),
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add avatar_approved on existing deployments
alter table public.profiles
  add column if not exists avatar_approved boolean not null default false;

-- Roles (adds column on existing deployments too)
alter table public.profiles
  add column if not exists role text not null default 'user' check (role in ('user', 'admin'));

-- Helper for admin policies
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles are viewable by everyone'
  ) then
    create policy "profiles are viewable by everyone"
    on public.profiles
    for select
    to public
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='users can insert their own profile'
  ) then
    create policy "users can insert their own profile"
    on public.profiles
    for insert
    to authenticated
    with check (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='users can update their own profile'
  ) then
    create policy "users can update their own profile"
    on public.profiles
    for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='admins can update profiles'
  ) then
    create policy "admins can update profiles"
    on public.profiles
    for update
    to authenticated
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

-- CATEGORIES
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row execute procedure public.set_updated_at();

alter table public.categories enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='categories' and policyname='categories are viewable by everyone'
  ) then
    create policy "categories are viewable by everyone"
    on public.categories
    for select
    to public
    using (true);
  end if;
end
$$;

-- POSTS
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles (id) on delete cascade,
  category_id bigint not null references public.categories (id) on delete restrict,
  title text not null,
  body text not null,
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Length constraints (defense in depth)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_title_len'
      and conrelid = 'public.posts'::regclass
  ) then
    alter table public.posts
      add constraint posts_title_len check (char_length(title) <= 200);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_body_len'
      and conrelid = 'public.posts'::regclass
  ) then
    alter table public.posts
      add constraint posts_body_len check (char_length(body) <= 15000) not valid;
  end if;
end
$$;

create index if not exists posts_author_id_idx on public.posts (author_id);
create index if not exists posts_category_id_idx on public.posts (category_id);
create index if not exists posts_created_at_idx on public.posts (created_at desc);

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row execute procedure public.set_updated_at();

alter table public.posts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='posts' and policyname='posts are viewable by everyone'
  ) then
    create policy "posts are viewable by everyone"
    on public.posts
    for select
    to public
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='posts' and policyname='users can create their own posts'
  ) then
    create policy "users can create their own posts"
    on public.posts
    for insert
    to authenticated
    with check (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='posts' and policyname='users can update their own posts'
  ) then
    create policy "users can update their own posts"
    on public.posts
    for update
    to authenticated
    using (auth.uid() = author_id)
    with check (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='posts' and policyname='users can delete their own posts'
  ) then
    create policy "users can delete their own posts"
    on public.posts
    for delete
    to authenticated
    using (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='posts' and policyname='admins can delete posts'
  ) then
    create policy "admins can delete posts"
    on public.posts
    for delete
    to authenticated
    using (public.is_admin(auth.uid()));
  end if;
end
$$;

-- COMMENTS
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null,
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Nested replies (adds column on existing projects too)
alter table public.comments
  add column if not exists parent_comment_id uuid references public.comments (id) on delete cascade;

-- Anonymous replies (adds column on existing projects too)
alter table public.comments
  add column if not exists is_anonymous boolean not null default false;

-- Replies are capped at 500 characters
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'comments_body_len'
      and conrelid = 'public.comments'::regclass
  ) then
    alter table public.comments
      add constraint comments_body_len check (char_length(body) <= 500) not valid;
  end if;
end
$$;

create index if not exists comments_post_id_idx on public.comments (post_id);
create index if not exists comments_author_id_idx on public.comments (author_id);
create index if not exists comments_parent_comment_id_idx on public.comments (parent_comment_id);
create index if not exists comments_created_at_idx on public.comments (created_at asc);

drop trigger if exists set_comments_updated_at on public.comments;
create trigger set_comments_updated_at
before update on public.comments
for each row execute procedure public.set_updated_at();

alter table public.comments enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='comments' and policyname='comments are viewable by everyone'
  ) then
    create policy "comments are viewable by everyone"
    on public.comments
    for select
    to public
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='comments' and policyname='users can create their own comments'
  ) then
    create policy "users can create their own comments"
    on public.comments
    for insert
    to authenticated
    with check (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='comments' and policyname='users can update their own comments'
  ) then
    create policy "users can update their own comments"
    on public.comments
    for update
    to authenticated
    using (auth.uid() = author_id)
    with check (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='comments' and policyname='users can delete their own comments'
  ) then
    create policy "users can delete their own comments"
    on public.comments
    for delete
    to authenticated
    using (auth.uid() = author_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='comments' and policyname='admins can delete comments'
  ) then
    create policy "admins can delete comments"
    on public.comments
    for delete
    to authenticated
    using (public.is_admin(auth.uid()));
  end if;
end
$$;

-- REACTIONS (like/upvote/etc)
do $$
begin
  if not exists (select 1 from pg_type where typname = 'reaction_target') then
    create type public.reaction_target as enum ('post', 'comment');
  end if;

  if not exists (select 1 from pg_type where typname = 'reaction_type') then
    create type public.reaction_type as enum ('like');
  end if;
end
$$;

create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  target public.reaction_target not null,
  post_id uuid references public.posts (id) on delete cascade,
  comment_id uuid references public.comments (id) on delete cascade,
  type public.reaction_type not null default 'like',
  created_at timestamptz not null default now(),
  constraint reactions_target_fk_check check (
    (target = 'post' and post_id is not null and comment_id is null) or
    (target = 'comment' and comment_id is not null and post_id is null)
  )
);

create index if not exists reactions_user_id_idx on public.reactions (user_id);
create index if not exists reactions_post_id_idx on public.reactions (post_id);
create index if not exists reactions_comment_id_idx on public.reactions (comment_id);

create unique index if not exists reactions_unique_user_post_like
on public.reactions (user_id, post_id, type)
where target = 'post';

create unique index if not exists reactions_unique_user_comment_like
on public.reactions (user_id, comment_id, type)
where target = 'comment';

alter table public.reactions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reactions' and policyname='reactions are viewable by everyone'
  ) then
    create policy "reactions are viewable by everyone"
    on public.reactions
    for select
    to public
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reactions' and policyname='users can create their own reactions'
  ) then
    create policy "users can create their own reactions"
    on public.reactions
    for insert
    to authenticated
    with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reactions' and policyname='users can delete their own reactions'
  ) then
    create policy "users can delete their own reactions"
    on public.reactions
    for delete
    to authenticated
    using (auth.uid() = user_id);
  end if;
end
$$;

-- REPORTS (user-submitted moderation flags)
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  post_id uuid references public.posts (id) on delete cascade,
  comment_id uuid references public.comments (id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'resolved', 'dismissed')),
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reports_target_check check (
    (target_type = 'post' and post_id is not null and comment_id is null) or
    (target_type = 'comment' and comment_id is not null)
  )
);

create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

drop trigger if exists set_reports_updated_at on public.reports;
create trigger set_reports_updated_at
before update on public.reports
for each row execute procedure public.set_updated_at();

alter table public.reports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reports' and policyname='authenticated users can view reports'
  ) then
    create policy "authenticated users can view reports"
    on public.reports
    for select
    to authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reports' and policyname='authenticated users can insert own reports'
  ) then
    create policy "authenticated users can insert own reports"
    on public.reports
    for insert
    to authenticated
    with check (auth.uid() = reporter_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='reports' and policyname='admins can update reports'
  ) then
    create policy "admins can update reports"
    on public.reports
    for update
    to authenticated
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

-- FEEDBACK (user-submitted feedback; anon inserts allowed)
create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  name text,
  message text not null,
  page_path text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='feedback' and policyname='feedback insert for all'
  ) then
    create policy "feedback insert for all"
    on public.feedback
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='feedback' and policyname='feedback select for authenticated'
  ) then
    create policy "feedback select for authenticated"
    on public.feedback
    for select
    to authenticated
    using (true);
  end if;
end
$$;

-- AVATARS STORAGE BUCKET
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152,  -- 2 MB
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
on conflict (id) do update set
  file_size_limit   = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage RLS: anyone can read; only the owner can upload/replace their own file
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars public read'
  ) then
    create policy "avatars public read"
    on storage.objects for select
    to public
    using (bucket_id = 'avatars');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars owner upload'
  ) then
    create policy "avatars owner upload"
    on storage.objects for insert
    to authenticated
    with check (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars owner update'
  ) then
    create policy "avatars owner update"
    on storage.objects for update
    to authenticated
    using (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars owner delete'
  ) then
    create policy "avatars owner delete"
    on storage.objects for delete
    to authenticated
    using (
      bucket_id = 'avatars'
      and (storage.foldername(name))[1] = auth.uid()::text
    );
  end if;
end
$$;

-- MOODS (mood check-in tool)
create table if not exists public.moods (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  mood text not null check (mood in ('great', 'good', 'okay', 'low', 'struggling')),
  created_at timestamptz not null default now()
);

create index if not exists moods_user_id_idx on public.moods (user_id);
create index if not exists moods_created_at_idx on public.moods (created_at desc);

alter table public.moods enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='moods' and policyname='users can view own moods'
  ) then
    create policy "users can view own moods"
    on public.moods
    for select
    to authenticated
    using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='moods' and policyname='users can insert own moods'
  ) then
    create policy "users can insert own moods"
    on public.moods
    for insert
    to authenticated
    with check (auth.uid() = user_id);
  end if;
end
$$;

-- Default categories
insert into public.categories (name, slug, description, sort_order)
values
  ('Vent', 'vent', 'A place to vent safely and be heard.', 10),
  ('Advice', 'advice', 'Ask for or share supportive advice.', 20),
  ('Wins', 'wins', 'Celebrate progress, big or small.', 30),
  ('College Life', 'college-life', 'Mental health discussions for college life.', 40)
on conflict (slug) do nothing;
