-- Mental health forum schema (Supabase / Postgres)
-- Includes tables: profiles, categories, posts, comments, reactions
-- Includes RLS policies so users can only edit/delete their own content

-- Extensions (safe if already enabled)
create extension if not exists "pgcrypto";

-- Helper: updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- PROFILES
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;

create policy "profiles are viewable by everyone"
on public.profiles
for select
to public
using (true);

create policy "users can insert their own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "users can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- CATEGORIES
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_categories_updated_at
before update on public.categories
for each row execute procedure public.set_updated_at();

alter table public.categories enable row level security;

create policy "categories are viewable by everyone"
on public.categories
for select
to public
using (true);

-- POSTS
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles (id) on delete cascade,
  category_id bigint not null references public.categories (id) on delete restrict,
  title text not null,
  body text not null,
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_author_id_idx on public.posts (author_id);
create index if not exists posts_category_id_idx on public.posts (category_id);
create index if not exists posts_created_at_idx on public.posts (created_at desc);

create trigger set_posts_updated_at
before update on public.posts
for each row execute procedure public.set_updated_at();

alter table public.posts enable row level security;

create policy "posts are viewable by everyone"
on public.posts
for select
to public
using (true);

create policy "users can create their own posts"
on public.posts
for insert
to authenticated
with check (auth.uid() = author_id);

create policy "users can update their own posts"
on public.posts
for update
to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

create policy "users can delete their own posts"
on public.posts
for delete
to authenticated
using (auth.uid() = author_id);

-- COMMENTS
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_post_id_idx on public.comments (post_id);
create index if not exists comments_author_id_idx on public.comments (author_id);
create index if not exists comments_created_at_idx on public.comments (created_at asc);

create trigger set_comments_updated_at
before update on public.comments
for each row execute procedure public.set_updated_at();

alter table public.comments enable row level security;

create policy "comments are viewable by everyone"
on public.comments
for select
to public
using (true);

create policy "users can create their own comments"
on public.comments
for insert
to authenticated
with check (auth.uid() = author_id);

create policy "users can update their own comments"
on public.comments
for update
to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

create policy "users can delete their own comments"
on public.comments
for delete
to authenticated
using (auth.uid() = author_id);

-- REACTIONS (like/upvote/etc)
do $$
begin
  if not exists (select 1 from pg_type where typname = 'reaction_target') then
    create type public.reaction_target as enum ('post', 'comment');
  end if;

  if not exists (select 1 from pg_type where typname = 'reaction_type') then
    create type public.reaction_type as enum ('like');
  end if;
end
$$;

create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  target public.reaction_target not null,
  post_id uuid references public.posts (id) on delete cascade,
  comment_id uuid references public.comments (id) on delete cascade,
  type public.reaction_type not null default 'like',
  created_at timestamptz not null default now(),
  constraint reactions_target_fk_check check (
    (target = 'post' and post_id is not null and comment_id is null) or
    (target = 'comment' and comment_id is not null and post_id is null)
  )
);

create index if not exists reactions_user_id_idx on public.reactions (user_id);
create index if not exists reactions_post_id_idx on public.reactions (post_id);
create index if not exists reactions_comment_id_idx on public.reactions (comment_id);

create unique index if not exists reactions_unique_user_post_like
on public.reactions (user_id, post_id, type)
where target = 'post';

create unique index if not exists reactions_unique_user_comment_like
on public.reactions (user_id, comment_id, type)
where target = 'comment';

alter table public.reactions enable row level security;

create policy "reactions are viewable by everyone"
on public.reactions
for select
to public
using (true);

create policy "users can create their own reactions"
on public.reactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users can delete their own reactions"
on public.reactions
for delete
to authenticated
using (auth.uid() = user_id);

-- Default categories
insert into public.categories (name, slug, description, sort_order)
values
  ('Vent', 'vent', 'A place to vent safely and be heard.', 10),
  ('Advice', 'advice', 'Ask for or share supportive advice.', 20),
  ('Wins', 'wins', 'Celebrate progress, big or small.', 30),
  ('College Life', 'college-life', 'Mental health discussions for college life.', 40)
on conflict (slug) do nothing;

-- REPORTS (user-submitted moderation flags)
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  post_id uuid references public.posts (id) on delete cascade,
  comment_id uuid references public.comments (id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'resolved', 'dismissed')),
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reports_target_check check (
    (target_type = 'post' and post_id is not null and comment_id is null) or
    (target_type = 'comment' and comment_id is not null)
  )
);

create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

create trigger set_reports_updated_at
before update on public.reports
for each row execute procedure public.set_updated_at();

alter table public.reports enable row level security;

create policy "authenticated users can view reports"
on public.reports
for select
to authenticated
using (true);

create policy "authenticated users can insert own reports"
on public.reports
for insert
to authenticated
with check (auth.uid() = reporter_id);

